/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as GiftsRouteImport } from './routes/gifts'
import { Route as BalanceRouteImport } from './routes/balance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoulettesIndexRouteImport } from './routes/roulettes/index'
import { Route as RoulettesIdRouteImport } from './routes/roulettes/$id'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftsRoute = GiftsRouteImport.update({
  id: '/gifts',
  path: '/gifts',
  getParentRoute: () => rootRouteImport,
} as any)
const BalanceRoute = BalanceRouteImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoulettesIndexRoute = RoulettesIndexRouteImport.update({
  id: '/roulettes/',
  path: '/roulettes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoulettesIdRoute = RoulettesIdRouteImport.update({
  id: '/roulettes/$id',
  path: '/roulettes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/balance': typeof BalanceRoute
  '/gifts': typeof GiftsRoute
  '/profile': typeof ProfileRoute
  '/roulettes/$id': typeof RoulettesIdRoute
  '/roulettes': typeof RoulettesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/balance': typeof BalanceRoute
  '/gifts': typeof GiftsRoute
  '/profile': typeof ProfileRoute
  '/roulettes/$id': typeof RoulettesIdRoute
  '/roulettes': typeof RoulettesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/balance': typeof BalanceRoute
  '/gifts': typeof GiftsRoute
  '/profile': typeof ProfileRoute
  '/roulettes/$id': typeof RoulettesIdRoute
  '/roulettes/': typeof RoulettesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/balance'
    | '/gifts'
    | '/profile'
    | '/roulettes/$id'
    | '/roulettes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/balance' | '/gifts' | '/profile' | '/roulettes/$id' | '/roulettes'
  id:
    | '__root__'
    | '/'
    | '/balance'
    | '/gifts'
    | '/profile'
    | '/roulettes/$id'
    | '/roulettes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BalanceRoute: typeof BalanceRoute
  GiftsRoute: typeof GiftsRoute
  ProfileRoute: typeof ProfileRoute
  RoulettesIdRoute: typeof RoulettesIdRoute
  RoulettesIndexRoute: typeof RoulettesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifts': {
      id: '/gifts'
      path: '/gifts'
      fullPath: '/gifts'
      preLoaderRoute: typeof GiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/balance': {
      id: '/balance'
      path: '/balance'
      fullPath: '/balance'
      preLoaderRoute: typeof BalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roulettes/': {
      id: '/roulettes/'
      path: '/roulettes'
      fullPath: '/roulettes'
      preLoaderRoute: typeof RoulettesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roulettes/$id': {
      id: '/roulettes/$id'
      path: '/roulettes/$id'
      fullPath: '/roulettes/$id'
      preLoaderRoute: typeof RoulettesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BalanceRoute: BalanceRoute,
  GiftsRoute: GiftsRoute,
  ProfileRoute: ProfileRoute,
  RoulettesIdRoute: RoulettesIdRoute,
  RoulettesIndexRoute: RoulettesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
